### ISSUE TITLE
[bug] Cannot connect to lighthouse due to "serve_dns"

### ISSUE THREAD

**Issue by KazamaSion** [slackhq/nebula#135]
Based on version: dev+20191224233758

Situation: turning on the "serve_dns" on the host can cause the connection failure to the lighthouse from the host.
In normal, after some "Handshake message sent" msg recorded, there will be a msg like "Handshake message received" appearing on the host.
After turning on the "serve_dns," no handshake msg will be received.

Config on the host(partially):
```
static_host_map:
  "192.168.71.2": ["127.0.0.1:12345"]
  # Just igore this 127.1 thing. Host and lighthouse host are not on the same machine.

lighthouse:
  am_lighthouse: false
  serve_dns: false
 # Here is the issue referring to 
  dns:
    host: 127.0.0.1
    port: 53
    # Not used by other application.
  interval: 20
  hosts:
    - "192.168.71.2"

listen:
  host: 127.0.0.1
  port: 0

punchy: true
punch_back: true
```

Config on the server(partially):
```
static_host_map:
  "192.168.71.99": ["127.0.0.1:24752"]

lighthouse:
  am_lighthouse: true
  serve_dns: true
  dns:
    host: 192.168.71.2
    port: 53
  interval: 20
  hosts:
    - "192.168.71.99"
    # I do this on purpose on the lighthouse host. 
    # And .99 is not the host referred before, it's another lighthouse host.

listen:
  host: 127.0.0.1
  port: fixed_port_here

punchy: true
punch_back: true
```

**Comment by rawdigits** [comment]
I can't reproduce this, and need configs with tokenized identifiers that aren't 127.0.0.1 if you want help debugging the config issue. You don't need to leave the original IPs in the config, but if key parts are all set as 127.0.0.1 as a form of redaction, it is impossible to differentiate them and determine what may be wrong.

**Comment by KazamaSion** [comment]
Server:
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:

lighthouse:
  am_lighthouse: true
  serve_dns: true
  dns:
    host: 127.0.0.1
    port: 53
  interval: 20
  hosts:

listen:
  host: 0.0.0.0
  port: 12345

punchy: true
punch_back: true

cipher: chachapoly

tun:
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```

Client (can launch successfully, can ping each other):
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "192.168.100.1": ["10.148.0.2:12345"]

lighthouse:
  am_lighthouse: false
  serve_dns: false
  # Note "serve_dns", this is the only difference
  dns:
    host: 127.0.0.1
    port: 53
  interval: 20
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 0

punchy: true
punch_back: true

cipher: chachapoly

tun:
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```

Client (fail to launch):
```
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "192.168.100.1": ["10.148.0.2:12345"]

lighthouse:
  am_lighthouse: false
  serve_dns: true
  dns:
    host: 127.0.0.1
    port: 53
  interval: 20
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 0

punchy: true
punch_back: true

cipher: chachapoly

tun:
  dev: neb0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
```

Log:
```
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:1 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:443 groups:[laptop home] host: ip:<nil> proto:6 startPort:443]"
INFO[0000] Firewall started                              firewallHash=016058fa4ea3aa02fb0ae0fae9542207c281f54942b7d1fb07263ba2f512785e
INFO[0000] Main HostMap created                          network=192.168.100.2/24 preferredRanges="[]"
INFO[0000] UDP hole punching enabled                    
INFO[0000] Nebula interface is active                    build=dev+20191224233758 interface=neb0 network=192.168.100.2/24
INFO[0000] Handshake message sent                        handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1371504957 remoteIndex=0 udpAddr="10.148.0.2:12345" vpnIp=192.168.100.1
INFO[0000] Handshake message received                    durationNs=303731774 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1371504957 remoteIndex=1371504957 responderIndex=3459658492 udpAddr="10.148.0.2:12345" vpnIp=192.168.100.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9bc526]

goroutine 18 [running]:
github.com/slackhq/nebula.(*dnsRecords).Add(0x0, 0xc000029f80, 0xc, 0xc000029f70, 0xd)
        github.com/slackhq/nebula@/dns_server.go:61 +0x26
github.com/slackhq/nebula.ixHandshakeStage2(0xc0000cc540, 0xc000029c78, 0xc0000cc6c0, 0xc00001d900, 0x113, 0x2329, 0xc000124a20, 0x0)
        github.com/slackhq/nebula@/handshake_ix.go:321 +0x1c10
github.com/slackhq/nebula.HandleIncomingHandshake(0xc0000cc540, 0xc000029c78, 0xc00001d900, 0x113, 0x2329, 0xc000124a20, 0x0)
        github.com/slackhq/nebula@/handshake.go:23 +0x10a
github.com/slackhq/nebula.(*Interface).readOutsidePackets(0xc0000cc540, 0xc000029c78, 0xc00001b400, 0x0, 0x2329, 0xc00001d900, 0x113, 0x2329, 0xc000124a20, 0xc000029c80, ...)
        github.com/slackhq/nebula@/outside.go:105 +0x3ef
github.com/slackhq/nebula.(*udpConn).ListenOut(0xc000029708, 0xc0000cc540)
        github.com/slackhq/nebula@/udp_linux.go:153 +0x1d5
github.com/slackhq/nebula.(*Interface).listenOut(0xc0000cc540, 0x0)
        github.com/slackhq/nebula@/interface.go:133 +0x7a
created by github.com/slackhq/nebula.(*Interface).Run
        github.com/slackhq/nebula@/interface.go:106 +0x43e
```

**Comment by rawdigits** [comment]
Ah, the dns thread appears to be crashing when the client connects to the server. Can you share the client certificate details? `nebula-cert print -path [file]`

**Comment by KazamaSion** [comment]
@rawdigits 
```
NebulaCertificate {
        Details {
                Name: test2
                Ips: [
                        192.168.100.2/24
                ]
                Subnets: []
                Groups: []
                Not before: 2019-12-27 18:21:39 +0000 UTC
                Not After: 2020-12-26 17:49:45 +0000 UTC
                Is CA: false
                Issuer: 7deb2b13a50d91b79d571194206c370e40bfc02e216ff3cca5141700687e14e6
                Public key: cb10c42bbd4393003dd4ed5478350b4c925f27a146a5be57dee9cd1e9f7bf850
        }
        Fingerprint: ff1f7ce170bc34429a4f797d451cec73ebc83af050c297714b94736911a5c8c8
        Signature: 7ab2c97fddb57bd9f8ab68f2a919bf48822216f1bbed2c1fb142d325e44df836e299ac51386b8e5bee5f95a2accc4bcb66bc42b9d7596471f132dc8746e8d702
}
```

```
NebulaCertificate {
        Details {
                Name: Myorganization, Inc
                Ips: []
                Subnets: []
                Groups: []
                Not before: 2019-12-27 17:49:46 +0000 UTC
                Not After: 2020-12-26 17:49:46 +0000 UTC
                Is CA: true
                Issuer: 
                Public key: 3fe8080868868db7970543e0c9db9f05480e96498cd3404648c98e6a7ef2e6c0
        }
        Fingerprint: 7deb2b13a50d91b79d571194206c370e40bfc02e216ff3cca5141700687e14e6
        Signature: d099ae4f5b43a30db517ab575ba9ca0c3fa6b32e216acf4e1298d366882fbba1116eaba3be245503d304782bb0ac50c41564615280363313d42d69209bce670c
}

```

**Comment by psi-4ward** [comment]
same here with `dev+20210415185321` on Buster.

**Comment by JohnMaguire** [comment]
@KazamaSion and @psi-4ward IIUC this issue is occurring when `am_lighthouse` is set to false and `serve_dns` is set to true. This is not a supported configuration and there should now be a warning when starting the Nebula client as opposed to a crash since v1.4.0 - https://github.com/slackhq/nebula/pull/433

If you're experiencing an issue with `serve_dns` crashes on a host configured as a Lighthouse, please feel free to open a new ticket!
