### ISSUE TITLE
Nebula: fatal error: runtime: out of memory during handshake

### ISSUE THREAD

**Issue by Tapanito** [slackhq/nebula#157]
Issue:
Nebula crashes with OOM error, during handshake with the Lighthouse.  

Nebula version: Master branch commit 5c126cd42b3f5be20037650ff78cf3b4052fc4be 
Operating system: Ubuntu 16.04

Nebula node configuration:
```
pki:
  ca: ca.crt
  cert: host.crt
  key: host.key

static_host_map:
  "10.2.2.1": ["192.168.1.1:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
  - "10.2.2.1"

listen:
  host: 0.0.0.0
  port: 4242

tun:
  dev: nebula2
  mtu: 1300
logging:
  # panic, fatal, error, warning, info, or debug. Default is info
  level: info
  # json or text formats currently available. Default is text
  format: text


# Nebula security group configuration
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any
```

Error log:

```
INFO[0000] Nebula interface is active                    build=dev+20200109161940 interface=nebula2 network=10.2.1.1/24
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb5d08a, 0x16)
	runtime/panic.go:774 +0x72
runtime.sysMap(0xc0c4000000, 0x4000000, 0x10c5058)
	runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x10ab340, 0xe000, 0x7f5db6d4ec01, 0x7f5db6d4f740)
	runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x10ab340, 0x7, 0xffffffff)
	runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x10ab340, 0x7, 0x10c5068, 0x7f5db4041098)
	runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x10ab340, 0x7, 0x450067, 0x7f5db4041098)
	runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:1093 +0x4c
runtime.systemstack(0x0)
	runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	runtime/proc.go:1146

goroutine 10 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:330 fp=0xc077a562b0 sp=0xc077a562a8 pc=0x45cb10
runtime.(*mheap).alloc(0x10ab340, 0x7, 0x10067, 0x2)
	runtime/mheap.go:1092 +0x8a fp=0xc077a56300 sp=0xc077a562b0 pc=0x4279fa
runtime.(*mcentral).grow(0x10ad0b8, 0x0)
	runtime/mcentral.go:255 +0x7b fp=0xc077a56340 sp=0xc077a56300 pc=0x41994b
runtime.(*mcentral).cacheSpan(0x10ad0b8, 0x0)
	runtime/mcentral.go:106 +0x2fe fp=0xc077a563a0 sp=0xc077a56340 pc=0x41946e
runtime.(*mcache).refill(0x7f5dc8c236d0, 0x67)
	runtime/mcache.go:138 +0x85 fp=0xc077a563c0 sp=0xc077a563a0 pc=0x418f15
runtime.(*mcache).nextFree(0x7f5dc8c236d0, 0x67, 0x4, 0x0, 0x0)
	runtime/malloc.go:854 +0x87 fp=0xc077a563f8 sp=0xc077a563c0 pc=0x40d867
runtime.mallocgc(0x2500, 0xa5a520, 0xc06b77f101, 0xc06b499a34)
	runtime/malloc.go:1022 +0x793 fp=0xc077a56498 sp=0xc077a563f8 pc=0x40e1a3
runtime.makeslice(0xa5a520, 0x2329, 0x2329, 0xc06b499a34)
	runtime/slice.go:49 +0x6c fp=0xc077a564c8 sp=0xc077a56498 pc=0x4473ec
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:89 +0x13b fp=0xc077a56718 sp=0xc077a564c8 pc=0x9d977b
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a56788 sp=0xc077a56718 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a57060 sp=0xc077a56788 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x40000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a57110 sp=0xc077a57060 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499a20, 0x4, 0x4, 0xc06b499a24, 0xc, 0xc, 0xc0c3ff5900, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a57198 sp=0xc077a57110 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a573e8 sp=0xc077a57198 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a57458 sp=0xc077a573e8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a57d30 sp=0xc077a57458 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x60000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a57de0 sp=0xc077a57d30 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499a10, 0x4, 0x4, 0xc06b499a14, 0xc, 0xc, 0xc0c3ff3400, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a57e68 sp=0xc077a57de0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a580b8 sp=0xc077a57e68 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a58128 sp=0xc077a580b8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a58a00 sp=0xc077a58128 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x30000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a58ab0 sp=0xc077a58a00 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499a00, 0x4, 0x4, 0xc06b499a04, 0xc, 0xc, 0xc0c3ff0f00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a58b38 sp=0xc077a58ab0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a58d88 sp=0xc077a58b38 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a58df8 sp=0xc077a58d88 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a596d0 sp=0xc077a58df8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x70000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a59780 sp=0xc077a596d0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999f0, 0x4, 0x4, 0xc06b4999f4, 0xc, 0xc, 0xc0c3feea00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a59808 sp=0xc077a59780 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a59a58 sp=0xc077a59808 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a59ac8 sp=0xc077a59a58 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5a3a0 sp=0xc077a59ac8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x40000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5a450 sp=0xc077a5a3a0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999e0, 0x4, 0x4, 0xc06b4999e4, 0xc, 0xc, 0xc0c3fec500, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5a4d8 sp=0xc077a5a450 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5a728 sp=0xc077a5a4d8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5a798 sp=0xc077a5a728 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5b070 sp=0xc077a5a798 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x50000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5b120 sp=0xc077a5b070 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999d0, 0x4, 0x4, 0xc06b4999d4, 0xc, 0xc, 0xc0c3fea000, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5b1a8 sp=0xc077a5b120 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5b3f8 sp=0xc077a5b1a8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5b468 sp=0xc077a5b3f8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5bd40 sp=0xc077a5b468 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0xa020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5bdf0 sp=0xc077a5bd40 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999c0, 0x4, 0x4, 0xc06b4999c4, 0xc, 0xc, 0xc0c3fe7900, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5be78 sp=0xc077a5bdf0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5c0c8 sp=0xc077a5be78 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5c138 sp=0xc077a5c0c8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5ca10 sp=0xc077a5c138 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x10000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5cac0 sp=0xc077a5ca10 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999b0, 0x4, 0x4, 0xc06b4999b4, 0xc, 0xc, 0xc0c3fe5400, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5cb48 sp=0xc077a5cac0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5cd98 sp=0xc077a5cb48 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5ce08 sp=0xc077a5cd98 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5d6e0 sp=0xc077a5ce08 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x10000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5d790 sp=0xc077a5d6e0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b4999a0, 0x4, 0x4, 0xc06b4999a4, 0xc, 0xc, 0xc0c3fe2f00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5d818 sp=0xc077a5d790 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5da68 sp=0xc077a5d818 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5dad8 sp=0xc077a5da68 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5e3b0 sp=0xc077a5dad8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x40000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5e460 sp=0xc077a5e3b0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499990, 0x4, 0x4, 0xc06b499994, 0xc, 0xc, 0xc0c3fe0a00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5e4e8 sp=0xc077a5e460 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5e738 sp=0xc077a5e4e8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5e7a8 sp=0xc077a5e738 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5f080 sp=0xc077a5e7a8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x70000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5f130 sp=0xc077a5f080 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499980, 0x4, 0x4, 0xc06b499984, 0xc, 0xc, 0xc0c3fde500, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5f1b8 sp=0xc077a5f130 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a5f408 sp=0xc077a5f1b8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a5f478 sp=0xc077a5f408 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a5fd50 sp=0xc077a5f478 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x70000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a5fe00 sp=0xc077a5fd50 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499970, 0x4, 0x4, 0xc06b499974, 0xc, 0xc, 0xc0c3fdc000, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a5fe88 sp=0xc077a5fe00 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a600d8 sp=0xc077a5fe88 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a60148 sp=0xc077a600d8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a60a20 sp=0xc077a60148 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x60000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a60ad0 sp=0xc077a60a20 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499960, 0x4, 0x4, 0xc06b499964, 0xc, 0xc, 0xc0c3fd9900, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a60b58 sp=0xc077a60ad0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a60da8 sp=0xc077a60b58 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a60e18 sp=0xc077a60da8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a616f0 sp=0xc077a60e18 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x40000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a617a0 sp=0xc077a616f0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499950, 0x4, 0x4, 0xc06b499954, 0xc, 0xc, 0xc0c3fd7400, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a61828 sp=0xc077a617a0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a61a78 sp=0xc077a61828 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a61ae8 sp=0xc077a61a78 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a623c0 sp=0xc077a61ae8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x70000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a62470 sp=0xc077a623c0 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499940, 0x4, 0x4, 0xc06b499944, 0xc, 0xc, 0xc0c3fd4f00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a624f8 sp=0xc077a62470 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a62748 sp=0xc077a624f8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a627b8 sp=0xc077a62748 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a63090 sp=0xc077a627b8 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x40000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a63140 sp=0xc077a63090 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499930, 0x4, 0x4, 0xc06b499934, 0xc, 0xc, 0xc0c3fd2a00, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a631c8 sp=0xc077a63140 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a63418 sp=0xc077a631c8 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a63488 sp=0xc077a63418 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a63d60 sp=0xc077a63488 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x50000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a63e10 sp=0xc077a63d60 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499920, 0x4, 0x4, 0xc06b499924, 0xc, 0xc, 0xc0c3fd0500, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a63e98 sp=0xc077a63e10 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a640e8 sp=0xc077a63e98 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a64158 sp=0xc077a640e8 pc=0x9d962f
github.com/slackhq/nebula.ixHandshakeStage0(0xc000162480, 0xc000000000, 0xc0000f0180)
	github.com/slackhq/nebula@/handshake_ix.go:20 +0x75 fp=0xc077a64a30 sp=0xc077a64158 pc=0x9c3905
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000162480, 0x10000000a020201, 0xffffffffffffffff)
	github.com/slackhq/nebula@/inside.go:86 +0x132 fp=0xc077a64ae0 sp=0xc077a64a30 pc=0x9d5c02
github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp(0xc000162480, 0xa02020100020003, 0xc06b499910, 0x4, 0x4, 0xc06b499914, 0xc, 0xc, 0xc0c3fce000, 0x2329, ...)
	github.com/slackhq/nebula@/inside.go:116 +0x3d fp=0xc077a64b68 sp=0xc077a64ae0 pc=0x9d615d
github.com/slackhq/nebula.(*LightHouse).QueryServer(0xc00006b140, 0xc000000000, 0xc57c60, 0xc000162480)
	github.com/slackhq/nebula@/lighthouse.go:91 +0x220 fp=0xc077a64db8 sp=0xc077a64b68 pc=0x9d9860
github.com/slackhq/nebula.(*LightHouse).Query(0xc00006b140, 0x0, 0xc57c60, 0xc000162480, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/slackhq/nebula@/lighthouse.go:67 +0x22f fp=0xc077a64e28 sp=0xc077a64db8 pc=0x9d962f
...additional frames elided...
created by github.com/slackhq/nebula.Main
	github.com/slackhq/nebula@/main.go:305 +0x1d27
```

**Comment by nbrownus** [comment]
How much memory does this system have? On a heavily loaded system (~27k tunnels) `nebula` is using ~200MB of memory. On a lightly loaded system (~75 tunnels) `nebula` is using ~63MB of memory.

**Comment by Tapanito** [comment]
This was running on a VM with 2GB of memory.  Version `1.0.0` establishes a connection to the lighthouse without any issues.

**Comment by rawdigits** [comment]
Did you generate your certificates for nodes with `-subnet` defined?

**Comment by wadey** [comment]
I think your issue is the one described in #170. You have a lighthouse defined that is not in the subnet defined in your host's cert. I'm guessing your host's VPN subnet does not contain 10.2.2.1? All hosts including the lighthouse need to be in the same VPN subnet.

**Comment by rawdigits** [comment]
@Tapanito I think our latest version fixes this, but take a look at what @wadey recommends and if you still see issues feel free to reopen this ticket. Thank you for reporting the bug!
