### ISSUE TITLE
Race condition:  handshake finishing while packet is processing

### ISSUE THREAD

**Issue by fm407** [slackhq/nebula#226]
```
ERRO[0080] Failed to call noise.WriteMessage             error="noise: unexpected call to WriteMessage should be ReadMessage" handshake="map[stage:0 style:ix_psk0]" vpnIp=10.10.70.82
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x989fde]
goroutine 29 [running]:
github.com/slackhq/nebula.ixHandshakeStage0(0xc0000f0480, 0xc00a3c5a52, 0xc0000f0300)
        github.com/slackhq/nebula/handshake_ix.go:41 +0x50e
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc0000f0480, 0xa0a1952, 0x2329)
        github.com/slackhq/nebula/inside.go:91 +0x132
github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0xc0000f0480, 0xc000246500, 0xc8, 0x2329, 0xc0002382e0, 0xc0002382f      0, 0xc, 0xc, 0xc000248a00, 0x2329, ...)
        github.com/slackhq/nebula/inside.go:32 +0xe6
github.com/slackhq/nebula.(*Interface).listenIn(0xc0000f0480, 0x0)
        github.com/slackhq/nebula/interface.go:155 +0x13a
created by github.com/slackhq/nebula.(*Interface).Run
        github.com/slackhq/nebula/interface.go:116 +0x59f
 ```

Operating System: Kali GNU/Linux Rolling
            Kernel: Linux 5.4.0-kali3-amd64
             Architecture: x86-64

Nebula Version: 1.2.0

**Comment by wadey** [comment]
I'm pretty sure the issue here is certState getting set to nil here while the new packet is processing: https://github.com/slackhq/nebula/blob/v1.2.0/hostmap.go#L568
