### ISSUE TITLE
Multiple data races found

### ISSUE THREAD

**Issue by darren** [slackhq/nebula#283]
There're panics during handshake:

```go
DEBU[0011] Hostmap index deleted                         hostMap="map[indexNumber:1651690631 mapName:main mapTotalSize:1]"
DEBU[0011] Sending 0 stored packets                      certName=lighthouse-03 vpnIp=10.8.1.252
DEBU[0011] Generated index                               index=2257837831
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1513f67]

goroutine 13 [running]:
github.com/slackhq/nebula.ixHandshakeStage0(0xc000312160, 0xc00a0801fc, 0xc0002c03c0)
        github.com/slackhq/nebula/handshake_ix.go:40 +0x5a7
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc000312160, 0xa0801fc, 0x2329)
        github.com/slackhq/nebula/inside.go:106 +0x13b
github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0xc000312160, 0xc0001ac000, 0x8c, 0x2329, 0xc0001ba000, 0xc0001ba010, 0xc, 0xc, 0xc0001ae500, 0x2329, ...)
        github.com/slackhq/nebula/inside.go:32 +0xf9
github.com/slackhq/nebula.(*Interface).listenIn(0xc000312160, 0x0)
        github.com/slackhq/nebula/interface.go:164 +0x13c
created by github.com/slackhq/nebula.(*Interface).Run
        github.com/slackhq/nebula/interface.go:125 +0x559
```

And enable race build found these data races:

```go
1. ==================
WARNING: DATA RACE
Read at 0x00c000348288 by goroutine 14:
  github.com/slackhq/nebula.(*HandshakeManager).handleOutbound()
      github.com/slackhq/nebula/handshake_manager.go:149 +0x3ed
  github.com/slackhq/nebula.(*HandshakeManager).NextOutboundHandshakeTimerTick()
      github.com/slackhq/nebula/handshake_manager.go:97 +0xb9
  github.com/slackhq/nebula.(*HandshakeManager).Run()
      github.com/slackhq/nebula/handshake_manager.go:83 +0x1ea

Previous write at 0x00c000348288 by goroutine 18:
  github.com/slackhq/nebula.ixHandshakeStage0()
      github.com/slackhq/nebula/handshake_ix.go:67 +0x13b6
  github.com/slackhq/nebula.(*Interface).getOrHandshake()
      github.com/slackhq/nebula/inside.go:106 +0x27a
  github.com/slackhq/nebula.(*Interface).consumeInsidePacket()
      github.com/slackhq/nebula/inside.go:32 +0x2e9
  github.com/slackhq/nebula.(*Interface).listenIn()
      github.com/slackhq/nebula/interface.go:164 +0x178
```

```go
2. ==================
WARNING: DATA RACE
Read at 0x00c00030bad0 by goroutine 14:
  runtime.mapaccess1()
      runtime/map.go:394 +0x0
  github.com/slackhq/nebula.(*HandshakeManager).handleOutbound()
      github.com/slackhq/nebula/handshake_manager.go:150 +0x511
  github.com/slackhq/nebula.(*HandshakeManager).NextOutboundHandshakeTimerTick()
      github.com/slackhq/nebula/handshake_manager.go:97 +0xb9
  github.com/slackhq/nebula.(*HandshakeManager).Run()
      github.com/slackhq/nebula/handshake_manager.go:83 +0x1ea

Previous write at 0x00c00030bad0 by goroutine 18:
  runtime.mapassign()
      runtime/map.go:571 +0x0
  github.com/slackhq/nebula.ixHandshakeStage0()
      github.com/slackhq/nebula/handshake_ix.go:66 +0x1351
  github.com/slackhq/nebula.(*Interface).getOrHandshake()
      github.com/slackhq/nebula/inside.go:106 +0x27a
  github.com/slackhq/nebula.(*Interface).consumeInsidePacket()
      github.com/slackhq/nebula/inside.go:32 +0x2e9
  github.com/slackhq/nebula.(*Interface).listenIn()
      github.com/slackhq/nebula/interface.go:164 +0x178
```

```go
3. ==================
WARNING: DATA RACE
Write at 0x00c00030e020 by goroutine 17:
  sync/atomic.AddInt64()
      runtime/race_amd64.s:276 +0xb
  github.com/slackhq/nebula.(*Interface).sendNoMetrics()
      github.com/slackhq/nebula/inside.go:226 +0x9c
  github.com/slackhq/nebula.(*Interface).send()
      github.com/slackhq/nebula/inside.go:214 +0x149
  github.com/slackhq/nebula.(*Interface).readOutsidePackets()
      github.com/slackhq/nebula/outside.go:94 +0x1213
  github.com/slackhq/nebula.(*udpConn).ListenOut()
      github.com/slackhq/nebula/udp_generic.go:109 +0x3b5
  github.com/slackhq/nebula.(*Interface).listenOut()
      github.com/slackhq/nebula/interface.go:147 +0x15e

Previous read at 0x00c00030e020 by goroutine 18:
  github.com/slackhq/nebula.(*Interface).consumeInsidePacket()
      github.com/slackhq/nebula/inside.go:58 +0x892
  github.com/slackhq/nebula.(*Interface).listenIn()
      github.com/slackhq/nebula/interface.go:164 +0x178
```

```go
4. ==================
WARNING: DATA RACE
Read at 0x00c00031a0e0 by goroutine 29:
  github.com/slackhq/nebula.(*HostInfo).TryPromoteBest()
      github.com/slackhq/nebula/hostmap.go:442 +0x7e
  github.com/slackhq/nebula.(*HostMap).queryVpnIP()
      github.com/slackhq/nebula/hostmap.go:296 +0x12f
  github.com/slackhq/nebula.(*HostMap).PromoteBestQueryVpnIP()
      github.com/slackhq/nebula/hostmap.go:289 +0x1a4
  github.com/slackhq/nebula.(*Interface).getOrHandshake()
      github.com/slackhq/nebula/inside.go:78 +0x15e
  github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp()
      github.com/slackhq/nebula/inside.go:150 +0x64
  github.com/slackhq/nebula.(*LightHouse).HandleRequest.func2()
      github.com/slackhq/nebula/lighthouse.go:404 +0x235

Previous write at 0x00c00031a0e0 by goroutine 18:
  github.com/slackhq/nebula.(*HostInfo).TryPromoteBest()
      github.com/slackhq/nebula/hostmap.go:442 +0x9e
  github.com/slackhq/nebula.(*HostMap).queryVpnIP()
      github.com/slackhq/nebula/hostmap.go:296 +0x12f
  github.com/slackhq/nebula.(*HostMap).PromoteBestQueryVpnIP()
      github.com/slackhq/nebula/hostmap.go:289 +0x1a4
  github.com/slackhq/nebula.(*Interface).getOrHandshake()
      github.com/slackhq/nebula/inside.go:78 +0x15e
  github.com/slackhq/nebula.(*Interface).consumeInsidePacket()
      github.com/slackhq/nebula/inside.go:32 +0x2e9
  github.com/slackhq/nebula.(*Interface).listenIn()
      github.com/slackhq/nebula/interface.go:164 +0x178
```

```go
5. ==================
WARNING: DATA RACE
Read at 0x00c0001b8684 by goroutine 14:
  github.com/slackhq/nebula.(*HostMap).GetIndexByVpnIP()
      github.com/slackhq/nebula/hostmap.go:107 +0x14a
  github.com/slackhq/nebula.(*HandshakeManager).handleOutbound()
      github.com/slackhq/nebula/handshake_manager.go:102 +0x76
  github.com/slackhq/nebula.(*HandshakeManager).NextOutboundHandshakeTimerTick()
      github.com/slackhq/nebula/handshake_manager.go:97 +0xb9
  github.com/slackhq/nebula.(*HandshakeManager).Run()
      github.com/slackhq/nebula/handshake_manager.go:83 +0x1ea

Previous write at 0x00c0001b8684 by goroutine 17:
  github.com/slackhq/nebula.(*HostMap).AddIndexHostInfo()
      github.com/slackhq/nebula/hostmap.go:191 +0x76
  github.com/slackhq/nebula.ixHandshakeStage2()
      github.com/slackhq/nebula/handshake_ix.go:363 +0x3791
  github.com/slackhq/nebula.HandleIncomingHandshake()
      github.com/slackhq/nebula/handshake.go:28 +0x2f8
  github.com/slackhq/nebula.(*Interface).readOutsidePackets()
      github.com/slackhq/nebula/outside.go:104 +0x679
  github.com/slackhq/nebula.(*udpConn).ListenOut()
      github.com/slackhq/nebula/udp_generic.go:109 +0x3b5
  github.com/slackhq/nebula.(*Interface).listenOut()
      github.com/slackhq/nebula/interface.go:147 +0x15e
```

```go
6. ==================
WARNING: DATA RACE
Read at 0x00c0001196d0 by goroutine 13:
  github.com/slackhq/nebula.(*Interface).getOrHandshake()
      github.com/slackhq/nebula/inside.go:90 +0x495
  github.com/slackhq/nebula.(*Interface).SendMessageToVpnIp()
      github.com/slackhq/nebula/inside.go:150 +0x64
  github.com/slackhq/nebula.(*connectionManager).HandleMonitorTick()
      github.com/slackhq/nebula/connection_manager.go:191 +0x925
  github.com/slackhq/nebula.(*connectionManager).Run()
      github.com/slackhq/nebula/connection_manager.go:146 +0xbd

Previous write at 0x00c0001196d0 by goroutine 17:
  github.com/slackhq/nebula.(*HostInfo).handshakeComplete()
      github.com/slackhq/nebula/hostmap.go:575 +0x427
  github.com/slackhq/nebula.ixHandshakeStage2()
      github.com/slackhq/nebula/handshake_ix.go:365 +0x37a4
  github.com/slackhq/nebula.HandleIncomingHandshake()
      github.com/slackhq/nebula/handshake.go:28 +0x2f8
  github.com/slackhq/nebula.(*Interface).readOutsidePackets()
      github.com/slackhq/nebula/outside.go:104 +0x679
  github.com/slackhq/nebula.(*udpConn).ListenOut()
      github.com/slackhq/nebula/udp_generic.go:109 +0x3b5
  github.com/slackhq/nebula.(*Interface).listenOut()
      github.com/slackhq/nebula/interface.go:147 +0x15e
```

```go
7. ==================
WARNING: DATA RACE
Read at 0x00c00015e1d8 by goroutine 14:
  github.com/slackhq/nebula.(*HandshakeManager).handleOutbound()
      github.com/slackhq/nebula/handshake_manager.go:113 +0x175e
  github.com/slackhq/nebula.(*HandshakeManager).NextOutboundHandshakeTimerTick()
      github.com/slackhq/nebula/handshake_manager.go:97 +0xb9
  github.com/slackhq/nebula.(*HandshakeManager).Run()
      github.com/slackhq/nebula/handshake_manager.go:83 +0x1ea

Previous write at 0x00c00015e1d8 by goroutine 17:
  github.com/slackhq/nebula.(*HostInfo).handshakeComplete()
      github.com/slackhq/nebula/hostmap.go:564 +0x99
  github.com/slackhq/nebula.ixHandshakeStage2()
      github.com/slackhq/nebula/handshake_ix.go:365 +0x37a4
  github.com/slackhq/nebula.HandleIncomingHandshake()
      github.com/slackhq/nebula/handshake.go:28 +0x2f8
  github.com/slackhq/nebula.(*Interface).readOutsidePackets()
      github.com/slackhq/nebula/outside.go:104 +0x679
  github.com/slackhq/nebula.(*udpConn).ListenOut()
      github.com/slackhq/nebula/udp_generic.go:109 +0x3b5
  github.com/slackhq/nebula.(*Interface).listenOut()
      github.com/slackhq/nebula/interface.go:147 +0x15e
```

```go
8. ==================
WARNING: DATA RACE
Write at 0x00c0000d4144 by goroutine 17:
  github.com/slackhq/nebula.(*HostMap).AddIndexHostInfo()
      /root/Sources/nebula/hostmap.go:191 +0x76
  github.com/slackhq/nebula.ixHandshakeStage2()
      /root/Sources/nebula/handshake_ix.go:363 +0x3791
  github.com/slackhq/nebula.HandleIncomingHandshake()
      /root/Sources/nebula/handshake.go:28 +0x2f8
  github.com/slackhq/nebula.(*Interface).readOutsidePackets()
      /root/Sources/nebula/outside.go:104 +0x679
  github.com/slackhq/nebula.(*udpConn).ListenOut()
      /root/Sources/nebula/udp_linux.go:165 +0x334
  github.com/slackhq/nebula.(*Interface).listenOut()
      /root/Sources/nebula/interface.go:147 +0x1e4

Previous read at 0x00c0000d4144 by goroutine 14:
  github.com/slackhq/nebula.(*HandshakeManager).handleOutbound()
      /root/Sources/nebula/handshake_manager.go:162 +0xff4
  github.com/slackhq/nebula.(*HandshakeManager).Run()
      /root/Sources/nebula/handshake_manager.go:81 +0x30e
```

**Comment by forfuncsake** [comment]
Hey @darren , can you please share which release or commit you were running in this scenario?

**Comment by darren** [comment]
@forfuncsake  lastest commit: 2e5a477a509a37faae2954161e3dd47e424ffa36, no edit

**Comment by forfuncsake** [comment]
I'm unable to reproduce on `darwin`/`linux` `amd64` when building with `go1.14.7` and `go1.15` with the race detector enabled.

**Comment by forfuncsake** [comment]
Can you share more details about your hardware/environment?

**Comment by darren** [comment]
Build with

`go build -race -trimpath -ldflags "-X main.Build=dev+20200817030548" -o ./nebula "./cmd/nebula"`

Tested on 

1. CentOS8 (kernel 4.18.0-147.8.1.el8_1.x86_64)
2. macOS 10.15.6 (19G2021) 

Both reproducible on my environment

config used:

```yaml
pki:
  ca: 
  cert:
  key:

static_host_map:
  "10.8.1.21": ["LH_IP:18942"]
  
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.8.1.21"

punchy:
  punch: true
  respond: true
  delay: 1s

cipher: chachapoly

tun:
  dev: ne0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 192.168.101.0/23
      via: 10.8.1.20
    - route: 192.168.102.0/24
      via: 10.8.1.21

logging:
  level: debug
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

    - port: any
      proto: any
      groups:
        - office
```

**Comment by forfuncsake** [comment]
and hardware? Can you `cat /proc/cpuinfo` please?

**Comment by darren** [comment]
CentOS 8
```processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E31220 @ 3.10GHz
stepping	: 7
microcode	: 0x1
cpu MHz		: 3110.146
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm cpuid_fault pti tsc_adjust xsaveopt arat umip arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 6220.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

macOS:   Mac mini 2018

**Comment by darren** [comment]
the original panic is a duplicate of #226

**Comment by bonedaddy** [comment]
I've been working on identifying races and fixing them, so far I've fixed 4 different race conditions, however I've found more during testing. Patching them here https://github.com/bonedaddy/nebula/pull/1 and can open a PR upstream (here) if desired.
