### ISSUE TITLE
ctrl-c on Windows crashes lighthouse

### ISSUE THREAD

**Issue by IngwiePhoenix** [slackhq/nebula#644]
Hello!

I wanted to set up a basic structure with one lighthouse and one node just to try things out. When I CTRL-C the client on my Windows maschine, this happens on my remote:

```
INFO[0007] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0007] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0007] Firewall started                              firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
INFO[0007] Main HostMap created                          network=192.168.100.1/24 preferredRanges="[]"
INFO[0007] UDP hole punching enabled
INFO[0007] Nebula interface is active                    build=1.5.2 interface=nebula1 network=192.168.100.1/24 udpAddr="[::]:4242"
INFO[0018] Handshake message received                    certName=ingwie-pc fingerprint=447fad9b15305d27d7bb1a7e3ed06f4b4f0c1b4b2c1cf8150bc66354d745cb07 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1171482022 issuer=04c5c6cede1ccc03afe015106c2a4dd9d71736541ca352e2bced7cfc7ddeede6 remoteIndex=0 responderIndex=0 udpAddr="77.190.50.151:4242" vpnIp=192.168.100.3
INFO[0018] Handshake message sent                        certName=ingwie-pc fingerprint=447fad9b15305d27d7bb1a7e3ed06f4b4f0c1b4b2c1cf8150bc66354d745cb07 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1171482022 issuer=04c5c6cede1ccc03afe015106c2a4dd9d71736541ca352e2bced7cfc7ddeede6 remoteIndex=0 responderIndex=3234825807 sentCachedPackets=0 udpAddr="77.190.50.151:4242" vpnIp=192.168.100.3
INFO[0018] Handshake message received                    certName=ingwie-pc fingerprint=447fad9b15305d27d7bb1a7e3ed06f4b4f0c1b4b2c1cf8150bc66354d745cb07 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1171482022 issuer=04c5c6cede1ccc03afe015106c2a4dd9d71736541ca352e2bced7cfc7ddeede6 remoteIndex=0 responderIndex=0 udpAddr="77.190.50.151:4242" vpnIp=192.168.100.3
INFO[0018] Handshake message sent                        cached=true handshake="map[stage:2 style:ix_psk0]" udpAddr="77.190.50.151:4242" vpnIp=192.168.100.3
INFO[0029] Close tunnel received, tearing down.          certName=ingwie-pc udpAddr="77.190.50.151:4242" vpnIp=192.168.100.3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9388e6]

goroutine 11 [running]:
github.com/slackhq/nebula.(*HostInfo).GetCert(...)
        github.com/slackhq/nebula/hostmap.go:490
github.com/slackhq/nebula.(*connectionManager).handleInvalidCertificate(0xc0c0a86403, {0xc07f5544e7089176, 0xaa181f, 0xfa7380}, 0x309c08, 0x0)
        github.com/slackhq/nebula/connection_manager.go:292 +0x46
github.com/slackhq/nebula.(*connectionManager).HandleMonitorTick(0xc00012ef80, {0xc07f55422704c2f5, 0x535a6d3d8, 0xfa7380}, {0xfd78a8, 0x0, 0x0}, {0xc0000ac110, 0xc, 0xc}, ...)
        github.com/slackhq/nebula/connection_manager.go:190 +0x18c
github.com/slackhq/nebula.(*connectionManager).Run(0x0, {0xb94d50, 0xc0001133c0})
        github.com/slackhq/nebula/connection_manager.go:160 +0x15a
created by github.com/slackhq/nebula.(*connectionManager).Start
        github.com/slackhq/nebula/connection_manager.go:144 +0x8f
```

I don't know what information I'd have to redact from the log, but I will re-create the certs and such anyway because I don't think that `192.168.100.x` is really what I want.

What is happening here that causes the lighthouse to crash like this? 

Thanks and kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
Revisited Nebula today and for some reason, now it works just fine?... Must've been an update to my kernel or something. But hey, its working now!
