### ISSUE TITLE
e2e test deadlock

### ISSUE THREAD

**Issue by wadey** [slackhq/nebula#671]
For some reason, it looks like the e2e tests sometimes deadlock on windows. See this example run:

- https://github.com/slackhq/nebula/runs/6080842414?check_suite_focus=true

We think this is perhaps an ordering issue, or timing with the quick handshake packet being sent along with the TimerWheel based one when the reading side only is expecting one of the handshake packets. We aren't sure why it only seems to trigger on Windows.

**Comment by brad-defined** [comment]
FWIW, I can repro on Mac, but it takes a few runs:
```
for i in {0..1000}
do
go test -tags="e2e_testing" -count=1 -timeout 2s -run Test_Case1_Stage1Race ./e2e
if [ $? -ne 0 ]; then
break
fi
done
```

So, I think it's more likely to hit on Windows, but not exclusive to Windows.

Becomes much less likely to hit (impossible?) if I increase the channel buffer sizes from 1 to 10 in the test udp/devices tun_tester.go, udp_tester.go.

**Comment by wadey** [comment]
Ah good to know, I hadn't had any luck reproducing on Linux so far. I'll see if I can reproduce enough to confirm that its just an issue with sending two handshake packets at the same time.

**Comment by brad-defined** [comment]
I repro'd with debug logging enabled, and I do see a handshake get re-sent:

`time="them 09:53:43.012106" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1332510497 udpAddrs="[10.0.0.1:4242]" vpnIp=10.128.0.1`
`time="them 09:53:43.212041" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1332510497 udpAddrs="[10.0.0.1:4242]" vpnIp=10.128.0.1`

here's the complete output:
```
time="me   09:53:42.710410" level=debug msg="Trusted CA fingerprints" fingerprints="[bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9]"
time="me   09:53:42.710553" level=debug msg="Client nebula certificate" cert="NebulaCertificate {\n\tDetails {\n\t\tName: me  \n\t\tIps: [\n\t\t\t10.128.0.1/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-04-20 09:53:42 -0400 EDT\n\t\tNot After: 2022-04-20 09:58:42 -0400 EDT\n\t\tIs CA: false\n\t\tIssuer: bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9\n\t\tPublic key: 68314ea190c803b5c8e7cf004cde22803ca4a5443de013f70b77bf9246c79405\n\t}\n\tFingerprint: 3e2544c24368744774b898a87d67407c7f2130b5be44ac4831bf1da543f94262\n\tSignature: 906de978f4c9d75d3fad1a5a136a7b658cf5b6f13417b20ef963a3ff0aeefb4e3dd0b0cff45169824e0b697f1fb444629104df1e0e7a973a8d131b79327a5106\n}"
time="me   09:53:42.710636" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="me   09:53:42.710648" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="me   09:53:42.710655" level=info msg="Firewall started" firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
time="me   09:53:42.710740" level=info msg="Main HostMap created" network=10.128.0.1/24 preferredRanges="[]"
time="me   09:53:42.710772" level=warning msg="No lighthouse.hosts configured, this host will only be able to initiate tunnels with static_host_map entries"
time="me   09:53:42.711036" level=trace msg=localAllowList.AllowName allow=true interfaceName=lo0
time="me   09:53:42.711052" level=trace msg=localAllowList.AllowName allow=true interfaceName=gif0
time="me   09:53:42.711064" level=trace msg=localAllowList.AllowName allow=true interfaceName=stf0
time="me   09:53:42.711069" level=trace msg=localAllowList.AllowName allow=true interfaceName=anpi1
time="me   09:53:42.711080" level=trace msg=localAllowList.AllowName allow=true interfaceName=anpi0
time="them 09:53:42.711081" level=debug msg="Trusted CA fingerprints" fingerprints="[bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9]"
time="me   09:53:42.711086" level=trace msg=localAllowList.AllowName allow=true interfaceName=ap1
time="me   09:53:42.711091" level=trace msg=localAllowList.AllowName allow=true interfaceName=en3
time="me   09:53:42.711096" level=trace msg=localAllowList.AllowName allow=true interfaceName=en4
time="me   09:53:42.711100" level=trace msg=localAllowList.AllowName allow=true interfaceName=en1
time="me   09:53:42.711107" level=trace msg=localAllowList.AllowName allow=true interfaceName=en2
time="me   09:53:42.711111" level=trace msg=localAllowList.AllowName allow=true interfaceName=en0
time="me   09:53:42.711118" level=trace msg=localAllowList.Allow allow=true localIp=192.168.95.26
time="me   09:53:42.711123" level=trace msg=localAllowList.AllowName allow=true interfaceName=awdl0
time="me   09:53:42.711133" level=trace msg=localAllowList.AllowName allow=true interfaceName=bridge0
time="me   09:53:42.711138" level=trace msg=localAllowList.AllowName allow=true interfaceName=llw0
time="me   09:53:42.711144" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun0
time="them 09:53:42.711137" level=debug msg="Client nebula certificate" cert="NebulaCertificate {\n\tDetails {\n\t\tName: them\n\t\tIps: [\n\t\t\t10.128.0.2/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-04-20 09:53:42 -0400 EDT\n\t\tNot After: 2022-04-20 09:58:42 -0400 EDT\n\t\tIs CA: false\n\t\tIssuer: bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9\n\t\tPublic key: 0a42f34931d96821d9217b5cfd95b09d784c2962729d6214c059ef20037cf406\n\t}\n\tFingerprint: c5f19defec5cdf059ac323eed42927c67e68eff8e7bd561dcba4184df4d8f844\n\tSignature: 512b64fd23066ac1198cfe043e1b782f308112b04a9f4f205dd1a60e3924cc968d068a60e4d2898146af3b3c1ed31a44c6fcf557bc3cb531754e8f75b0482100\n}"
time="me   09:53:42.711150" level=trace msg=localAllowList.Allow allow=true localIp=100.64.0.2
time="me   09:53:42.711153" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun1
time="me   09:53:42.711163" level=trace msg=localAllowList.Allow allow=true localIp=10.255.0.3
time="them 09:53:42.711162" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="me   09:53:42.711166" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun3
time="them 09:53:42.711170" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="them 09:53:42.711177" level=info msg="Firewall started" firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
time="them 09:53:42.711185" level=info msg="Main HostMap created" network=10.128.0.2/24 preferredRanges="[]"
time="them 09:53:42.711190" level=warning msg="No lighthouse.hosts configured, this host will only be able to initiate tunnels with static_host_map entries"
time="me   09:53:42.711173" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun4
time="me   09:53:42.711216" level=info msg="Nebula interface is active" build=e2e-test interface= network=10.128.0.1/24 udpAddr="10.0.0.1:4242"
time="me   09:53:42.711221" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun5
time="me   09:53:42.711231" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun6
time="me   09:53:42.711238" level=trace msg=localAllowList.Allow allow=true localIp=172.16.201.3
time="me   09:53:42.711243" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun2
time="them 09:53:42.711244" level=info msg="Nebula interface is active" build=e2e-test interface= network=10.128.0.2/24 udpAddr="10.0.0.2:4242"
time="me   09:53:42.711250" level=trace msg=localAllowList.Allow allow=true localIp=172.16.200.3
    handshakes_test.go:147: Trigger a handshake to start on both me and them
time="them 09:53:42.711283" level=trace msg=localAllowList.AllowName allow=true interfaceName=lo0
time="them 09:53:42.711303" level=trace msg=localAllowList.AllowName allow=true interfaceName=gif0
time="them 09:53:42.711314" level=trace msg=localAllowList.AllowName allow=true interfaceName=stf0
time="them 09:53:42.711320" level=trace msg=localAllowList.AllowName allow=true interfaceName=anpi1
time="them 09:53:42.711327" level=trace msg=localAllowList.AllowName allow=true interfaceName=anpi0
time="them 09:53:42.711332" level=trace msg=localAllowList.AllowName allow=true interfaceName=ap1
time="them 09:53:42.711337" level=trace msg=localAllowList.AllowName allow=true interfaceName=en3
time="them 09:53:42.711342" level=trace msg=localAllowList.AllowName allow=true interfaceName=en4
time="them 09:53:42.711347" level=trace msg=localAllowList.AllowName allow=true interfaceName=en1
time="them 09:53:42.711353" level=trace msg=localAllowList.AllowName allow=true interfaceName=en2
time="me   09:53:42.711304" level=info msg="Tun receiving injected packet" dataLen=38
time="them 09:53:42.711358" level=trace msg=localAllowList.AllowName allow=true interfaceName=en0
time="them 09:53:42.711366" level=trace msg=localAllowList.Allow allow=true localIp=192.168.95.26
time="them 09:53:42.711369" level=trace msg=localAllowList.AllowName allow=true interfaceName=awdl0
time="them 09:53:42.711377" level=trace msg=localAllowList.AllowName allow=true interfaceName=bridge0
time="them 09:53:42.711383" level=trace msg=localAllowList.AllowName allow=true interfaceName=llw0
time="them 09:53:42.711388" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun0
time="them 09:53:42.711384" level=info msg="Tun receiving injected packet" dataLen=40
    handshakes_test.go:151: Get both stage 1 handshake packets
time="them 09:53:42.711395" level=trace msg=localAllowList.Allow allow=true localIp=100.64.0.2
time="them 09:53:42.711416" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun1
time="them 09:53:42.711424" level=trace msg=localAllowList.Allow allow=true localIp=10.255.0.3
time="them 09:53:42.711427" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun3
time="them 09:53:42.711435" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun4
time="them 09:53:42.711442" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun5
time="them 09:53:42.711449" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun6
time="them 09:53:42.711455" level=trace msg=localAllowList.Allow allow=true localIp=172.16.201.3
time="them 09:53:42.711482" level=trace msg=localAllowList.AllowName allow=true interfaceName=utun2
time="them 09:53:42.711496" level=trace msg=localAllowList.Allow allow=true localIp=172.16.200.3
time="them 09:53:42.711586" level=debug msg="Generated index" index=1332510497
time="me   09:53:42.711616" level=debug msg="Generated index" index=4236651546
time="them 09:53:42.711720" level=debug msg="Packet store" length=1 stored=true vpnIp=10.128.0.1
time="me   09:53:42.711754" level=debug msg="Packet store" length=1 stored=true vpnIp=10.128.0.2
time="them 09:53:43.012106" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1332510497 udpAddrs="[10.0.0.1:4242]" vpnIp=10.128.0.1
time="them 09:53:43.212041" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1332510497 udpAddrs="[10.0.0.1:4242]" vpnIp=10.128.0.1
    handshakes_test.go:155: Now inject both stage 1 handshake packets
time="me   09:53:43.212007" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4236651546 udpAddrs="[10.0.0.2:4242]" vpnIp=10.128.0.2
time="me   09:53:43.212134" level=info msg="UDP receiving injected packet" dataLen=233 header="ver=1 type=handshake subtype=ix_psk0 reserved=0x0 remoteindex=0 messagecounter=1" udpAddr="10.0.0.2:4242"
time="them 09:53:43.212201" level=info msg="UDP receiving injected packet" dataLen=233 header="ver=1 type=handshake subtype=ix_psk0 reserved=0x0 remoteindex=0 messagecounter=1" udpAddr="10.0.0.1:4242"
    handshakes_test.go:160: They should not have a stage 2 (won the race) but I should send one
time="them 09:53:43.213052" level=debug msg="Generated index" index=1239149602
time="me   09:53:43.213054" level=debug msg="Generated index" index=1343203940
time="them 09:53:43.213110" level=info msg="Handshake message received" certName="me  " fingerprint=3e2544c24368744774b898a87d67407c7f2130b5be44ac4831bf1da543f94262 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4236651546 issuer=bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9 remoteIndex=0 responderIndex=0 udpAddr="10.0.0.1:4242" vpnIp=10.128.0.1
time="me   09:53:43.213171" level=info msg="Handshake message received" certName=them fingerprint=c5f19defec5cdf059ac323eed42927c67e68eff8e7bd561dcba4184df4d8f844 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1332510497 issuer=bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9 remoteIndex=0 responderIndex=0 udpAddr="10.0.0.2:4242" vpnIp=10.128.0.2
time="them 09:53:43.214405" level=error msg="Prevented a pending handshake race" certName="me  " fingerprint=3e2544c24368744774b898a87d67407c7f2130b5be44ac4831bf1da543f94262 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4236651546 issuer=bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9 remoteIndex=0 responderIndex=1239149602 udpAddr="10.0.0.1:4242" vpnIp=10.128.0.1
time="me   09:53:43.214458" level=debug msg="Hostmap hostInfo deleted" hostMap="map[indexNumber:4236651546 mapName:pending mapTotalSize:0 remoteIndexNumber:0 vpnIp:10.128.0.2]"
time="me   09:53:43.214511" level=info msg="Handshake race lost, replacing pending handshake with completed tunnel" vpnIp=10.128.0.2
time="me   09:53:43.214532" level=debug msg="Hostmap vpnIp added" hostMap="map[hostinfo:map[existing:true hostId:10.128.0.2 localIndexId:1343203940] mapName:main mapTotalSize:1 vpnIp:10.128.0.2]"
time="me   09:53:43.214607" level=info msg="Handshake message sent" certName=them fingerprint=c5f19defec5cdf059ac323eed42927c67e68eff8e7bd561dcba4184df4d8f844 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1332510497 issuer=bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9 remoteIndex=0 responderIndex=1343203940 sentCachedPackets=1 udpAddr="10.0.0.2:4242" vpnIp=10.128.0.2
time="me   09:53:43.214648" level=debug msg="Sending 1 stored packets" certName=them vpnIp=10.128.0.2
time="them 09:53:43.214718" level=info msg="UDP receiving injected packet" dataLen=271 header="ver=1 type=handshake subtype=ix_psk0 reserved=0x0 remoteindex=1332510497 messagecounter=2" udpAddr="10.0.0.1:4242"
    handshakes_test.go:163: Route for me until I send a message packet to them
time="them 09:53:43.214784" level=info msg="UDP receiving injected packet" dataLen=70 header="ver=1 type=message subtype=none reserved=0x0 remoteindex=1332510497 messagecounter=3" udpAddr="10.0.0.1:4242"
    handshakes_test.go:166: My cached packet should be received by them
time="them 09:53:43.216116" level=info msg="Handshake message received" certName="me  " durationNs=504351125 fingerprint=3e2544c24368744774b898a87d67407c7f2130b5be44ac4831bf1da543f94262 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1332510497 issuer=bf2ce703a66fef637304ba8a5f0c6489400e02e9b66453f649d59012e4deb9c9 remoteIndex=1332510497 responderIndex=1343203940 sentCachedPackets=1 udpAddr="10.0.0.1:4242" vpnIp=10.128.0.1
time="them 09:53:43.216192" level=debug msg="Hostmap vpnIp added" hostMap="map[hostinfo:map[existing:true hostId:10.128.0.1 localIndexId:1332510497] mapName:main mapTotalSize:1 vpnIp:10.128.0.1]"
time="them 09:53:43.216228" level=debug msg="Hostmap hostInfo deleted" hostMap="map[indexNumber:1332510497 mapName:pending mapTotalSize:0 remoteIndexNumber:1343203940 vpnIp:10.128.0.1]"
time="them 09:53:43.216261" level=debug msg="Sending 1 stored packets" certName="me  " vpnIp=10.128.0.1
panic: test timed out after 2s

goroutine 66 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0x8c
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x3c

goroutine 1 [chan receive]:
testing.(*T).Run(0x14000282820, {0x104d46db8?, 0xb3b4e8e7c6c8?}, 0x104fe0130)
	/usr/local/go/src/testing/testing.go:1487 +0x314
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1839 +0x74
testing.tRunner(0x14000282820, 0x14000151cb8)
	/usr/local/go/src/testing/testing.go:1439 +0x110
testing.runTests(0x14000298780?, {0x105464280, 0x3, 0x3}, {0x6100000000000000?, 0x10472efd8?, 0x10546e720?})
	/usr/local/go/src/testing/testing.go:1837 +0x3f0
testing.(*M).Run(0x14000298780)
	/usr/local/go/src/testing/testing.go:1719 +0x500
main.main()
	_testmain.go:51 +0x1d0

goroutine 35 [chan receive]:
github.com/slackhq/nebula/overlay.(*TestTun).Get(0x140002829c0?, 0x38?)
	/Users/bradleyhiggins/Work/nebula/overlay/tun_tester.go:61 +0x7c
github.com/slackhq/nebula.(*Control).GetFromTun(...)
	/Users/bradleyhiggins/Work/nebula/control_tester.go:68
github.com/slackhq/nebula/e2e.Test_Case1_Stage1Race(0x140002829c0)
	/Users/bradleyhiggins/Work/nebula/e2e/handshakes_test.go:167 +0x478
testing.tRunner(0x140002829c0, 0x104fe0130)
	/usr/local/go/src/testing/testing.go:1439 +0x110
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x300

goroutine 5 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:148 +0x30
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x30

goroutine 6 [select]:
github.com/slackhq/nebula/config.(*C).CatchHUP.func1()
	/Users/bradleyhiggins/Work/nebula/config/config.go:124 +0xc0
created by github.com/slackhq/nebula/config.(*C).CatchHUP
	/Users/bradleyhiggins/Work/nebula/config/config.go:122 +0xe0

goroutine 7 [select]:
github.com/slackhq/nebula.(*connectionManager).Run(0x0?, {0x104fea738, 0x140002c8f00})
	/Users/bradleyhiggins/Work/nebula/connection_manager.go:156 +0x150
created by github.com/slackhq/nebula.(*connectionManager).Start
	/Users/bradleyhiggins/Work/nebula/connection_manager.go:144 +0x98

goroutine 8 [select]:
github.com/slackhq/nebula.(*HandshakeManager).Run(0x14000148500, {0x104fea738, 0x140002c8f00}, {0x104fe4c98, 0x1400023e120})
	/Users/bradleyhiggins/Work/nebula/handshake_manager.go:78 +0xd8
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:305 +0x1b54

goroutine 9 [select]:
github.com/slackhq/nebula.(*LightHouse).LhUpdateWorker(0x140001640e0, {0x104fea738?, 0x140002c8f00}, {0x104fe4c98?, 0x1400023e120})
	/Users/bradleyhiggins/Work/nebula/lighthouse.go:565 +0x1bc
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:306 +0x1bf4

goroutine 10 [select]:
github.com/slackhq/nebula.(*Interface).emitStats(0x1400023e120, {0x104fea738, 0x140002c8f00}, 0x0?)
	/Users/bradleyhiggins/Work/nebula/interface.go:316 +0xc8
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:322 +0x1cc4

goroutine 11 [select]:
github.com/slackhq/nebula/config.(*C).CatchHUP.func1()
	/Users/bradleyhiggins/Work/nebula/config/config.go:124 +0xc0
created by github.com/slackhq/nebula/config.(*C).CatchHUP
	/Users/bradleyhiggins/Work/nebula/config/config.go:122 +0xe0

goroutine 12 [select]:
github.com/slackhq/nebula.(*connectionManager).Run(0x0?, {0x104fea738, 0x140000434c0})
	/Users/bradleyhiggins/Work/nebula/connection_manager.go:156 +0x150
created by github.com/slackhq/nebula.(*connectionManager).Start
	/Users/bradleyhiggins/Work/nebula/connection_manager.go:144 +0x98

goroutine 13 [select]:
github.com/slackhq/nebula.(*HandshakeManager).Run(0x14000148800, {0x104fea738, 0x140000434c0}, {0x104fe4c98, 0x140002625a0})
	/Users/bradleyhiggins/Work/nebula/handshake_manager.go:78 +0xd8
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:305 +0x1b54

goroutine 14 [select]:
github.com/slackhq/nebula.(*LightHouse).LhUpdateWorker(0x140001647e0, {0x104fea738?, 0x140000434c0}, {0x104fe4c98?, 0x140002625a0})
	/Users/bradleyhiggins/Work/nebula/lighthouse.go:565 +0x1bc
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:306 +0x1bf4

goroutine 15 [select]:
github.com/slackhq/nebula.(*Interface).emitStats(0x140002625a0, {0x104fea738, 0x140000434c0}, 0x0?)
	/Users/bradleyhiggins/Work/nebula/interface.go:316 +0xc8
created by github.com/slackhq/nebula.Main
	/Users/bradleyhiggins/Work/nebula/main.go:322 +0x1cc4

goroutine 16 [chan receive, locked to thread]:
github.com/slackhq/nebula/udp.(*Conn).ListenOut(0x1400007d0e0, 0x14000559f98, 0x0?, 0x0?, 0x0?)
	/Users/bradleyhiggins/Work/nebula/udp/udp_tester.go:117 +0x154
github.com/slackhq/nebula.(*Interface).listenOut(0x1400023e120, 0x0)
	/Users/bradleyhiggins/Work/nebula/interface.go:199 +0x288
created by github.com/slackhq/nebula.(*Interface).run
	/Users/bradleyhiggins/Work/nebula/interface.go:177 +0x34

goroutine 50 [chan receive, locked to thread]:
github.com/slackhq/nebula/overlay.(*TestTun).Read(0x1400023e120?, {0x14000484a00, 0x2329, 0x2329?})
	/Users/bradleyhiggins/Work/nebula/overlay/tun_tester.go:110 +0x38
github.com/slackhq/nebula.(*Interface).listenIn(0x1400023e120, {0x12ce1fff8, 0x1400007ec80}, 0x0?)
	/Users/bradleyhiggins/Work/nebula/interface.go:213 +0x104
created by github.com/slackhq/nebula.(*Interface).run
	/Users/bradleyhiggins/Work/nebula/interface.go:182 +0xac

goroutine 51 [chan send, locked to thread]:
github.com/slackhq/nebula/udp.(*Conn).WriteTo(0x1400007dc00, {0x140003e6a00, 0x48, 0x2329?}, 0x140003b6340)
	/Users/bradleyhiggins/Work/nebula/udp/udp_tester.go:105 +0x348
github.com/slackhq/nebula.(*Interface).sendNoMetrics(0x140002625a0, 0x1, 0xc0?, 0x14000390900, 0x14000520000, 0x140003b6340, {0x140003dc030, 0x28, 0x28}, {0x1400039a6f0, ...}, ...)
	/Users/bradleyhiggins/Work/nebula/inside.go:226 +0x24c
github.com/slackhq/nebula.(*Interface).sendMessageNow(0x140002625a0, 0x0?, 0x25?, 0x14000520000, {0x140003dc030, 0x28, 0x28}, {0x1400039a6f0, 0xc, 0xc}, ...)
	/Users/bradleyhiggins/Work/nebula/inside.go:149 +0x284
github.com/slackhq/nebula.(*HostInfo).handshakeComplete(0x14000520000, 0x14000520000?, 0x1400007df80)
	/Users/bradleyhiggins/Work/nebula/hostmap.go:477 +0x2c4
github.com/slackhq/nebula.ixHandshakeStage2(0x140002625a0, 0x140002b2a00, 0x14000520000, {0x14000566240, 0x10f, 0x10f}, 0x140002b67b0)
	/Users/bradleyhiggins/Work/nebula/handshake_ix.go:461 +0x17b8
github.com/slackhq/nebula.HandleIncomingHandshake(0x140002625a0, 0x140002b2a00, {0x14000566240, 0x10f, 0x10f}, 0x140002b67b0, 0x0?)
	/Users/bradleyhiggins/Work/nebula/handshake.go:22 +0xe4
github.com/slackhq/nebula.(*Interface).readOutsidePackets(0x140002625a0, 0x140002b2a00, {0x14000372a00, 0x0, 0x2329}, {0x14000566240, 0x10f, 0x10f}, 0x140002b67b0, 0x140002b4fb0?, ...)
	/Users/bradleyhiggins/Work/nebula/outside.go:108 +0x2ac
github.com/slackhq/nebula/udp.(*Conn).ListenOut(0x1400007dc00, 0x1400045df98, 0x0?, 0x0?, 0x0?)
	/Users/bradleyhiggins/Work/nebula/udp/udp_tester.go:120 +0x140
github.com/slackhq/nebula.(*Interface).listenOut(0x140002625a0, 0x0)
	/Users/bradleyhiggins/Work/nebula/interface.go:199 +0x288
created by github.com/slackhq/nebula.(*Interface).run
	/Users/bradleyhiggins/Work/nebula/interface.go:177 +0x34

goroutine 52 [chan receive, locked to thread]:
github.com/slackhq/nebula/overlay.(*TestTun).Read(0x140002625a0?, {0x14000016a00, 0x2329, 0x2329?})
	/Users/bradleyhiggins/Work/nebula/overlay/tun_tester.go:110 +0x38
github.com/slackhq/nebula.(*Interface).listenIn(0x140002625a0, {0x12ce1fff8, 0x1400007f360}, 0x0?)
	/Users/bradleyhiggins/Work/nebula/interface.go:213 +0x104
created by github.com/slackhq/nebula.(*Interface).run
	/Users/bradleyhiggins/Work/nebula/interface.go:182 +0xac
FAIL	github.com/slackhq/nebula/e2e	2.017s
FAIL
```
